permalink: pretty
title: 'UsabilityHub'
google_analytics_id: ''
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop_height: 62px
  desktop: "images/logo/logo.svg"
footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'
collections:
  services:
    output: true
  team:
    output: true
sass:
  indentWidth: 4
  style: compact
  precision: 10
plugins:
  - jekyll-environment-variables
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
