name: "Build index page"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip install -r ./generator/requirements.txt

      - name: Build index
        run: python ./generator/generator.py

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install Jekyll
        run: gem install jekyll

      - name: Build website
        run: bundle exec jekyll build

      - name: Copy website
        run: cp -r _site/* build/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build