name: "Build index page"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build website
        uses: helaili/jekyll-action@v2
        with:
          build_only: true
          jekyll_src: website

      - name: Install requirements
        run: pip install -r ./generator/requirements.txt

      - name: Build index
        run: python ./generator/generator.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: website/build
